### ISSUE TITLE
Colcon build in ROS2 Foxy

### ISSUE THREAD

**Issue by CatInTheRain** [norlab-ulaval/ros2_tcp_tunnel#1]
Hi! Thanks for this wonderfull packet! It is very useful for large data transfer. It is possible to have a branch for foxy distribution? I have problem during compilation with colcon build. Thank you

**Comment by simonpierredeschenes** [comment]
Hi @CatInTheRain, thank you for your interest! I had started to work on a foxy branch, but was stuck because the rclcpp::GenericSubscription and rclcpp::GenericPublisher classes, which are used in this package, were introduced in Humble. However, there might be a workaround. I will try to spend a bit more time on it and see if I can find a solution.

**Comment by simonpierredeschenes** [comment]
Hi @CatInTheRain! I have some good news: I was able to fix the issues I had with the GenericSubscription and GenericPublisher classes, so the foxy branch should be functional now. I tested it by transferring point clouds over wifi and everything seemed fine. I will close this issue for now, but if you run into any problem, don't hesitate to re-open it or create a new one. Cheers!

**Comment by CatInTheRain** [comment]
Thanks a lot! Good work!
